### ISSUE TITLE
Node version errors

### ISSUE THREAD

**Issue by mohdhallal** [edarioq/dt-one#1]
hello @edarioq !

Thanks a bunch for this repo. While trying to run the app locally I am getting some errors pointing towards the node version I am using to build the app (16.6.2). 

Mind sharing the node version this application is compatible with, please?

Cheers

**Comment by edarioq** [comment]
OK got it, I'll check as soon as I get home. Thought it was current LTS but will double check.

**Comment by edarioq** [comment]
@mohdhallal `v14.15.5` - I just cloned it myself and it should install correctly. If anything you could try deleting the`package-lock.json` file.

**Comment by mohdhallal** [comment]
thanks @edarioq ! worked.
